/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    colors: {
      'bg-dark': '#635985',
      'bg-light': '#BDCDD6',
      'nav-bg-dark': '#18122B',
      'nav-bg-light': '#6096B4',
      'todos-bg-dark': '#18122B',
      'todos-bg-light': '#6096B4',
      'todoUl-bg-dark': '#18122B',
      'todoUl-bg-light': '#6096B4',
      'todoLi-bg-dark': '#443C68',
      'todoLi-bg-light': '#93BFCF',
      'todoLi-text-dark': '#EEE9DA',
      'todoLi-text-light': '#393053',
      'nav-text-dark': '#635985',
      'nav-text-light': '#EEE9DA',
      'text-dark': '#EEE9DA',
      'text-light': '#6096B4',
      'text-hover-dark': '#BDCDD6',
      'text-hover-light': '#93BFCF',
      'button-text-dark': '#BDCDD6',
      'button-text-light': '#EEE9DA',
      'button-bg-dark': '#443C68',
      'button-bg-light': '#93BFCF',
      'button-delete-bg-dark': '#8C1500',
      'button-delete-bg-light': '#FF6347',
      'button-delete-hover-dark': '#B21B00',
      'button-delete-hover-light': '#D9391C',
      'button-bg-hover-dark': '#93BFCF',
      'button-bg-hover-light': '#0097B2',
      'button-nav-bg-hover-dark': '#393053',
      'button-nav-bg-hover-light': '#BDCDD6',
      'input-text-dark': '#18122B',
      'input-text-light': '#18122B',

      //   // current: 'currentColor',
    },
    extend: {},
  },
  plugins: [],
}
